### ISSUE TITLE
Can we get travel reimbursement?

### ISSUE THREAD

**Issue by Hardolaf** [stupidhackathon/stupidhackathon.github.io#1]
Is it possible to reimburse travel to come make stupid ideas a reality?

**Comment by egladman** [comment]
bump

**Comment by joshuahhh** [comment]
We have no money, so I am sorry to say that the answer is "no". If you're not too far, you might want to arrange carpools via the [Facebook event](https://www.facebook.com/events/1567576990198712/) or nascent [Noisebridge wiki page](https://noisebridge.net/wiki/Stupid_Hackathon).

(Regardless, I hope the spirit of perverse endeavor lives on, wherever you may be, and that you might someday have the chance to throw your own Regional Stupid Event.)
