### ISSUE TITLE
license

### ISSUE THREAD

**Issue by dylang** [stupidhackathon/stupidhackathon.github.io#3]
I'd like to run one in Washington, DC but I'm not sure if it's cool to fork your site.

off topic - the videos were great. must have been a lot of work to edit that many videos but I really appreciated it.

**Comment by loganwilliams** [comment]
Hey dylang! Sorry we didn't see this, I think we all kind of stopped checking the Github after the event. I hope the license concern didn't stop you from hosting your own event. We're licensed under the WTFPL. We should add that.
